### ISSUE TITLE
Version 2.0.4 fails with ` Cannot find module '../parcel_sourcemap_node/index'`

### ISSUE THREAD

**Issue by michaelschufi** [parcel-bundler/source-map#107]
I have just installed parcel (`npm i -D parcel`) and got the error `Error: Cannot find module '../parcel_sourcemap_node/index'` (see below) when running `npx parcel build`.

After some investigation, I found that the error happens only with the newest `@parcel/source-map` version `2.0.4`.
Fixing it temporarily with `"@parcel/source-map": "2.0.2",` in `package.json` works.

Node Version used: `v16.15.0`
Parcel Version used: `2.5.0` and `2.4.0` (same error)

```
Error: Cannot find module '../parcel_sourcemap_node/index'
Require stack:
- /path/to/project/node_modules/@parcel/source-map/dist/node.js
- /path/to/project/node_modules/@parcel/utils/lib/index.js
- /path/to/project/node_modules/@parcel/core/lib/public/Config.js
- /path/to/project/node_modules/@parcel/core/lib/utils.js
- /path/to/project/node_modules/@parcel/core/lib/public/Environment.js
- /path/to/project/node_modules/@parcel/core/lib/public/Asset.js
- /path/to/project/node_modules/@parcel/core/lib/Parcel.js
- /path/to/project/node_modules/@parcel/core/lib/index.js
- /path/to/project/node_modules/parcel/lib/cli.js
- /path/to/project/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/project/node_modules/@parcel/source-map/dist/node.js:14:18)
    at Module._compile (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/project/node_modules/@parcel/source-map/dist/node.js',
    '/path/to/project/node_modules/@parcel/utils/lib/index.js',
    '/path/to/project/node_modules/@parcel/core/lib/public/Config.js',
    '/path/to/project/node_modules/@parcel/core/lib/utils.js',
    '/path/to/project/node_modules/@parcel/core/lib/public/Environment.js',
    '/path/to/project/node_modules/@parcel/core/lib/public/Asset.js',
    '/path/to/project/node_modules/@parcel/core/lib/Parcel.js',
    '/path/to/project/node_modules/@parcel/core/lib/index.js',
    '/path/to/project/node_modules/parcel/lib/cli.js',
    '/path/to/project/node_modules/parcel/lib/bin.js'
  ]
}
```

**Comment by LekoArts** [comment]
See https://github.com/parcel-bundler/parcel/issues/8114 - should be fixed with 2.0.5
